spring:
  application:
    name: gateway-service    
  main:
    allow-bean-definition-overriding: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/desire-job
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: discovery-service
          uri: http://localhost:8082/discovery-service
          predicates:
          - Path=/discovery-service/**
          filters:
          - TokenRelay=
          - RemoveRequestHeader=Cookie
        - id: book-service
          uri: http://localhost:8083/book-service
          predicates:
          - Path=/book-service/**
          filters:
          - TokenRelay=
          - RemoveRequestHeader=Cookie
        - id: user-service
          uri: http://localhost:8084/user-service
          predicates:
          - Path=/user-service/**
          filters:
          - TokenRelay=
          - RemoveRequestHeader=Cookie
        - id: openapi
          uri: http://localhost:8080
          predicates:
            - Path=/api-docs/**
          filters:
            - RewritePath=/api-docs/(?<path>.*), /$\{path}/api-docs
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411/    
    service:
      name: gateway-service
    sender:
      type: rabbit
    storage:
      type: elasticsearch
      elasticsearch:
        hosts: localhost:9200            
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: admin      

eureka:  
  client:
    region: default
    registryFetchIntervalSeconds: 20  
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://admin:admin@localhost:8082/discovery-service/eureka/


springdoc:
  enable-native-support: true
  api-docs:
    groups:
      enabled: true
    enabled: true
    path: /api-docs
  group-configs:
    - group: book-service
      paths-to-match:
        - /book-service/**
      display-name: Book Service
    - group: user-service
      paths-to-match:
        - /user-service/**
      display-name: User Service
  swagger-ui:
    config-url: /api-docs/swagger-config
    url: /api-docs
    path: /swagger-ui/index.html
    urls:
      - name: book-service
        url: /book-service/api-docs
      - name: user-service
        url: /user-service/api-docs

server:
  port: 8080
  forward-headers-strategy: framework  
  servlet:
    context-path:
