spring:
  application:
    name: gateway-service    
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters: TokenRelay=
      routes:
        - id: discovery-service
          uri: localhost:8082/discovery-service
          predicates:
          - Path=/discovery-service/**
        - id: book-service
          uri: localhost:8083/book-service
          predicates:
          - Path=/book-service/**
        - id: user-service
          uri: localhost:8084/user-service
          predicates:
          - Path=/user-service/**
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411/    
    service:
      name: gateway-service
    sender:
      type: rabbit
    storage:
      type: elasticsearch
      elasticsearch:
        hosts: localhost:9200            
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: admin      

eureka:  
  client:
    region: default
    registryFetchIntervalSeconds: 20  
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://admin:admin@localhost:8082/discovery-service/eureka/


springdoc:
  api-docs:
    enabled: true    
  swagger-ui:    
    urls:      
      - name: book-service
        url: /book-service/api-docs
      - name: user-service
        url: /user-service/api-docs

server:
  port: 8080
  forward-headers-strategy: framework  
  servlet:
    context-path:
